### ISSUE TITLE
bootstrapAsync doesn't affect the appLoader

### ISSUE THREAD

**Issue by d3fkon** [xamantra/momentum#14]
As per the documentation, the `appLoader` widget should be shown till the `bootstrapAsync` method of a controller finishes executing. But, it does not seem to work.

The following is my code snippet from main.dart:

```dart
    Momentum(
      controllers: <MomentumController<dynamic>>[
        AuthController()..config(lazy: false)
      ],
      services: [StorageService()],
      appLoader: MaterialApp(
        home: Scaffold(
          backgroundColor: Colors.black,
          body: Center(
            child: CircularProgressIndicator(),
          ),
        ),
      ),
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          accentColor: Colors.indigoAccent,
          primaryColor: Colors.green,
          textTheme: GoogleFonts.montserratTextTheme(),
        ),
        home: Root(),
      ),
    ),
```

The following is the snippet from the controller.dart file

```dart
@override
  Future<void> bootstrapAsync() async {
    await getService<StorageService>().init();
    final token = getService<StorageService>().getAuthToken();
    if (token == null) {
      model.update(
        token: null,
        isAuthenticated: false,
      );
    } else {
      model.update(
        token: token,
        isAuthenticated: true,
      );
    }
    await Future.delayed(const Duration(seconds: 10));
    return super.bootstrapAsync();
  }
```

I expected a 10 second circular progress bar. But it see the progress bar for about 200 ms.

**Comment by xamantra** [comment]
I can't reproduce this issue. I tried replicating everything from your code. And it works fine, though I don't know what's inside `StorageService`'s `init()` and `getAuthToken()`, but I think no matter what inside those methods, the appLoader should display because of 10 seconds mock delay in the code. And there's nothing wrong with your code either.

Here's my code for the storage service:
```dart
class StorageService extends MomentumService {
  Future<void> init() async {
    await Future.delayed(Duration(milliseconds: 3000));
  }

  String getAuthToken() {
    return 'dummy-token-only';
  }
}
```

The `bootstrapAsync()` implementation directly copy-pasted from your snippet:
```dart
  @override
  Future<void> bootstrapAsync() async {
    await getService<StorageService>().init();
    final token = getService<StorageService>().getAuthToken();
    if (token == null) {
      model.update(
        token: null,
        isAuthenticated: false,
      );
    } else {
      model.update(
        token: token,
        isAuthenticated: true,
      );
    }
    await Future.delayed(const Duration(seconds: 10));
    return super.bootstrapAsync();
  }
```

And here's the `Momentum` widget config:
```dart
    Momentum(
      controllers: <MomentumController<dynamic>>[
        AuthController()..config(lazy: false),
      ],
      enableLogging: true, // I enabled the logging.
      services: [
        StorageService(),
      ],
      appLoader: MaterialApp(
        home: Scaffold(
          backgroundColor: Colors.black,
          body: Center(
            child: CircularProgressIndicator(),
          ),
        ),
      ),
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          accentColor: Colors.indigoAccent,
          primaryColor: Colors.green,
          // textTheme: GoogleFonts.montserratTextTheme(),
        ),
        home: HomeWidget(),
      ),
    ),
```

Everything worked fine, here's the log I get from the console:
```bash
I/flutter ( 4369): [Momentum -> 'AuthController'] has been initialized. {maxTimeTravelSteps: 1}
I/flutter ( 4369): [Momentum -> 'AuthController'] => bootstrap() called! { lazy: false }
I/flutter ( 4369): [Momentum -> 'AuthController'] => executing bootstrapAsync() { lazy: false } ...
I/flutter ( 4369): [Momentum -> 'AuthController'] the model "AuthModel" has been updated, listeners => ACTIVE: 0 (notified), INACTIVE: 0 (ignored)
I/flutter ( 4369): [Momentum -> 'AuthController'] => bootstrapAsync() completed! { lazy: false, took: 13025ms }
```

<br>
May I know what version of momentum you are using? Maybe it's a bug from previous versions.
If you added the 10 seconds delay after everything else and hot restarted the app, maybe it's a bug from your code editor? That a new code change wasn't properly applied. Because I also experienced long ago with flutter. If that's the case try to flutter clean.

**Comment by d3fkon** [comment]
That's rather weird. I'm completely in love with this library for state management, except for this one bootstrap issue.
Here is my momentum version:
`momentum: 1.2.7`

And here is my platform and flutter version
`Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.19041.329], locale en-US)`

I tested it by creating a new project, but the issue seems to still exist. Let me run a few more tests and get back

**Comment by xamantra** [comment]
do you have any updates on this? you're still experiencing the issue? @d3fkon

**Comment by d3fkon** [comment]
```
I/flutter ( 4355): [Momentum -> 'AuthController'] has been initialized. {maxTimeTravelSteps: 1}
I/flutter ( 4355): [Momentum -> 'AuthController'] => bootstrap() called! { lazy: false }
I/flutter ( 4355): [Momentum -> 'AuthController'] => executing bootstrapAsync() { lazy: false } ...
I/flutter ( 4355): Before await Future.delayed()
I/flutter ( 4355): After await Future.delayed()
I/flutter ( 4355): [Momentum -> 'AuthController'] => bootstrapAsync() completed! { lazy: false, took: 10119ms }

```
I got the same logs, but the `appLoader` doesn't show up in the meantime. Isn't that the expected behaviour?
I created a new project with the same structure. But to no avail.

**Comment by d3fkon** [comment]
I went through `momentum_base.dart`. The library implementation seems fine. That's why I tested further 

![I completely restart the app in the gif](https://user-images.githubusercontent.com/23007190/86538056-31dae600-bf11-11ea-862f-8070aaf00c17.gif)
The loading screen only shows for about 4 seconds, when the delay in my `bootstrapAsync` is `Duration(seconds: 10)`

The quirk here is, I changed the delay to Duration(milliseconds: 10000), and it behaved as expected. This isn't an issue with the library, rather probably dart? I have no idea.

I tested it multiple times with changing between `milliseconds` and `seconds`, and the result was the same. `milliseconds` works as expected, while `seconds` doesn't.
Golly moses

**Comment by xamantra** [comment]
I will try to look into this.

**Comment by xamantra** [comment]
I really can't reproduce it at all. I changed between `seconds` and `milliseconds`  and they both worked as expected.

**Comment by d3fkon** [comment]
I guess it was an one-off issue. It still exists in my project right now. 
I don't think it's a problem with the library.

**Comment by RicardoRB** [comment]
@xamantra I have the same problem but just with iOS device, same code works in Android thought.
