### ISSUE TITLE
Async documentation is kind of confusing

### ISSUE THREAD

**Issue by exts** [xamantra/momentum#17]
I was reading it and it said future builder might not be needed, but no where does it show how you're executing `loadingSomeData`. I checked the listify example and the source code and there's no magic being applied here. 

Is there something missing from the documentation here: https://xamdev.gq/momentum/#/asynchronous

My guess was the call was meant to be inside of a `initMomentumState` before the builder was ran. But you forgot to create the example code for that.

**Comment by xamantra** [comment]
I mean, the point is `loadingSomeBigData()` is an asynchronous function, it's a future. No matter what's inside of it, the point is you just imagine that something is going on in there, and the execution has a delay. Most of the code in the docs is only the core ideas, not copy-pastable codes.

**Comment by exts** [comment]
> Edit: Ok, I just woke up and realize I was reading your issue wrong :) .. I'll include a quick fix for this one on the next release.

Yeah no worries. I figured you were doing something like the following in mind, but missed a small documentation piece explaining when you'd call `loadingSomeData`:

```dart
class LabelManagerScreen extends StatefulWidget {
  _LabelManagerScreenState createState() => _LabelManagerScreenState();
}

class _LabelManagerScreenState extends MomentumState<LabelManagerScreen> {
  LabelIndexController indexController;

  @override
  void initMomentumState() {
    super.initMomentumState();
    indexController = Momentum.controller<LabelIndexController>(context);
    indexController.getLabels();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Manage Labels"),
      ),
      body: MomentumBuilder(
        controllers: [LabelIndexController],
        builder: (context, snapshot) {
          var model = snapshot<LabelIndexModel>();
          if (model.loadingResults) {
            return Center(
              child: CircularProgressIndicator(),
            );
          }

          if (model.labels.length <= 0) {
            return Center(
              child: Text("No labels exist"),
            );
          }

          return Padding(
            padding: const EdgeInsets.all(5.0),
            child: ReorderableListView(
              children: List.generate(model.labels.length, (index) {
                var label = indexController.model.labels[index];
                return Dismissible(
                  onDismissed: (_) {
                      indexController.deleteLabel(label);
                      indexController.getLabels();
                    }
                  },
                  key: Key("${label.id}"),
                  child: LabelListCard(
                    title: label.labelName,
                  ),
                );
              }),
              onReorder: (idx, newIdx) {
                indexController.reorderLabels(idx, newIdx);
              },
            ),
          );
        },
      ),
    );
  }
}
```

```dart
class LabelIndexModel extends MomentumModel<LabelIndexController> {
  final bool loadingResults;
  final List<LabelData> labels;

  LabelIndexModel(
    LabelIndexController controller, {
    this.loadingResults,
    this.labels,
  }) : super(controller);

  @override
  void update({bool loadingResult, List<LabelData> labels}) {
    LabelIndexModel(
      controller,
      loadingResults: loadingResult ?? this.loadingResults,
      labels: labels ?? this.labels,
    ).updateMomentum();
  }
}
```

```dart
class LabelIndexController extends MomentumController<LabelIndexModel> {
  LabelRepository labelRepo;

  @override
  LabelIndexModel init() {
    labelRepo = getService<LabelRepository>();

    return LabelIndexModel(
      this,
      loadingResults: false,
    );
  }

  void getLabels() async {
    model.update(loadingResult: true);
    var labels = await labelRepo.getLabels();
    model.update(loadingResult: false, labels: labels);
  }

  // ... SNIP ...
}
```

tbh, I'm still unsure if my approach w/ sqlite is the best, but so far it's working alright.

**Comment by xamantra** [comment]
You're `getLabels()` method and its usage seems fine. But, `labelRepo = getService<LabelRepository>();` should be placed inside `bootstrap()` method instead of `init()`.

```dart
void bootstrap() {
  labelRepo = getService<LabelRepository>();
}
```

But based on what you said, calling `getService<T>()` inside `init()` is working but internally, it's not tested by momentum.

**Comment by exts** [comment]
Ah okay, thanks :)

**Comment by exts** [comment]
Ah, after doing more investigating (sorry for using this thread as a source for examples), but I've come to understanding how things should properly work the momentum way :) - essentially you want to bootstrap things you want to happen when the app first start. Which can be done lazily (by default) or if you need something loaded right when the app starts like in my example below we can do that check and it gets called only once. This is also where you'd want to load any necessary data because the controllers states persist for as long as the app is running. This is where I got confused when I was adding new items. Essentially you just want to make a call to `getLabels` after adding a new item in my case to update the index controllers state and we can await that so it loads before we leave the page. Same with dismissing items and deleting items. 

```dart
class LabelIndexController extends MomentumController<LabelIndexModel> {
  LabelRepository labelRepo;

  @override
  void bootstrap() {
    super.bootstrap();
    labelRepo = getService<LabelRepository>();
  }

  @override
  Future<void> bootstrapAsync() async {
    super.bootstrapAsync();
    // must be created if it doesn't exist before getting here
    await labelRepo.createDefaultLabelIfMissing(); 
    await getLabels();
  }

  @override
  LabelIndexModel init() {
    return LabelIndexModel(
      this,
      labels: List<LabelData>(),
      loadingResults: false,
    );
  }

  Future<void> getLabels() async {
    model.update(loadingResult: true);
    var labels = await labelRepo.getLabels();
    model.update(loadingResult: false, labels: labels);
  }

  /// ... SNIPPED .... dismiss, reorder, etc...
} 
```   

```dart
void main() {
  runApp(
    Momentum(
      disabledPersistentState: true, // because I'm using sqflite - this doesn't disable router goto though
      controllers: [
        LabelManageController(),
        LabelIndexController()..config(lazy: false), // we want to run this to run when the app starts so we disable lazy, else it'll load bootstrap the first time we make a call to this controller.
      ],
      services: [
        Router([
          IndexScreen(),
          LabelManagerScreen(), // uses label index controller to load data
          LabelManagerAddScreen(), // both use LabelManagerController
          LabelManagerUpdateScreen(), // both use LabelManagerController
        ]),
        LabelRepository(),
      ],
      child: MyApp(),
    ),
  );
}
```

Honestly, I'm going to open source my manage labels code for my app I'm working on which uses sqflite to show off how I've come to understand how to use momentum after the few comments you made about bootstrap. I'm also sure I could probably improve a lot in some areas regarding the models because I have a ton of boiler plate w/ my data objects. Will make one last comment after this because I think that's exactly what I'm going to do this morning before I work on my app some more.

**Comment by xamantra** [comment]
I published a new version on pub.dev: [v1.2.8](https://pub.dev/packages/momentum/changelog#128)

You can revisit the [docs](https://xamdev.gq/momentum/#/asynchronous) to review the changes.
