### ISSUE TITLE
Feature Request: Selective persistance

### ISSUE THREAD

**Issue by d3fkon** [xamantra/momentum#21]
Currently, `persistSave` gets called each time `model.update` is triggered. This forces all models to be persisted, regardless of which model it is. 

There are two cases why we would need selective persistence:  
- One, I have an `AuthModel` and a `AppModel`. I don't really want to persist `AuthModel` because I run validation checks when the app starts and make a request to the server. But I definitely want to persist the `AppModel` each time `model.update` is called.

- Second, I use `Hive` to store my `AppModel` because it's pretty complex and `FlutterSecureStorage` for `AuthModel` for it's added security in iOS. In the current version of `momentum`, I have my hands tied regarding which persistence mechanism I can use, as I don't know which model I'm persisting in the RunTime

So I suggest that passing the type of `MomentumModel` along with the `persistSave` call, so we can better tailor it to the need of the application.

**Comment by xamantra** [comment]
You can turn off persistence for specific model using `skipPersist()` virtual method.

```dart
class AuthController extends MomentumController<AuthModel> {
  
  // ...

 Future<bool> skipPersist() => true;

  // ...

}
```

You can also disable persistence for a specific property in a model by not adding it to the JSON serializer.

```dart
class LoginModel extends MomentumModel<LoginController> {

  // ...

  Map<String, dynamic> toJson() {
    return {
      'username': username,
      'password': '', // do not persist password, just save as an empty string.
    };
  }

  LoginModel fromJson(Map<String, dynamic> json) {
    return LoginModel(
      controller,
      username: json['username'],
      password: '', // do not persist password, just save as an empty string.
    );
  }

  // ...
}
```

**Comment by d3fkon** [comment]
I understand that, but if I want to use different persistence mechanisms for each model, this wouldn't suffice, right?

**Comment by xamantra** [comment]
You can do that @d3fkon.

`MomentumController` has [persistenceKey](https://xamdev.gq/momentum/#/momentum-controller?id=persistencekey) public readonly property, but you can *override* it.

Take a look at this example:

```dart
class AuthController extends MomentumController<AuthModel> {

  // ...

  @override
  String get persistenceKey => 'AuthModelPersistenceKey'; // and of course you can put anything in here.

  // ...

}
```

The `Momentum` config:

```dart
Momentum(
  // ...
  persistSave: (context, key, value) async {
    bool result;
    if (key == 'AuthModelPersistenceKey') {
      // save the "value" into different mechanism here...
      result = await secureStorage.setString(value);
    } else {
      // else just save normally... 
      result = await sharedPref.setString(value);
    }
    return result;
  },
  persistGet: (context, key) async {
    String result;
    if (key == 'AuthModelPersistenceKey') {
      // save the "value" into different mechanism here...
      result = await secureStorage.getString(value);
    } else {
      // else just save normally... 
      result = await sharedPref.getString(value);
    }
    return result;
  }
  // ...
)
```

And it is highly recommended to use *constant* strings.

```dart
// top level variable.
const String AuthModelPersistKey = 'AuthModelPersistenceKey';

// ...

@override
String get persistenceKey => AuthModelPersistKey;

// ...

if (key == AuthModelPersistKey) {
  // ...
}
```

**Comment by d3fkon** [comment]
I wasn't aware of that. That should solve the problem for now. An optional parameter which had the type of the model would've been more intuitive instead of managing strings. But that would be a breaking change to the current API. 
This should do it
