### ISSUE TITLE
Make controllers in momentum builder optional

### ISSUE THREAD

**Issue by exts** [xamantra/momentum#22]
![image](https://user-images.githubusercontent.com/16387107/88181940-2bc55480-cbf5-11ea-82f7-adcf2611676a.png)

It can already accept an empty list and nothing happens when you don't pass anything **but the IDE complains**; Why not just make it optional because sometimes you might instantiate the whole controller in a momentum state object which makes the call to snapshot almost unnecessary at times. I get there's many ways you could set it up, I just notice the way I've been working with momentum I do a lot of initiating of controllers before using them and access what I need w/out actually using snapshot (or making direct calls to model) as much as I would or should.

I have an example: I have a screen which has only one purpose and that's to add an item to the database, complain on any errors and then redirect to another route. Since it's using TextFields + TextEditingControllers it's not displaying much directly from the model which doesn't warrant a direct call to the model itself from outside of the controller.

Shouldn't be a breaking change either and probably a two second change since you already handle null controller values after checking the source.

**Comment by xamantra** [comment]
It's just `@required` decorator really. hehe. I can just remove it. And doesn't really affect anything at all. Yeah when I was writing momentum, I did a lot of runtime checks and linter decorators for the devs to follow. maybe I overdid some parts. I'm fine with this.

**Comment by exts** [comment]
Forgot to mention @xamantra will need to update a small part of the docs too :) https://xamdev.gq/momentum/#/momentum-builder?id=controllers

**Comment by xamantra** [comment]
You can now check this update on your projects. Try to use the `dev-1.3.1` channel for momentum:

```yaml
dependencies:
  flutter:
    sdk: flutter
  momentum:
    git:
      url: https://github.com/xamantra/momentum.git
      ref: dev-1.3.1
```

**Comment by exts** [comment]
Alright one moment

**Comment by xamantra** [comment]
This update is now live on [pub.dev - v1.3.1](https://pub.dev/packages/momentum/versions/1.3.1). Will now be closed.
