### ISSUE TITLE
Exception has occurred. _AssertionError (Failed assertion: boolean expression must not be null)

### ISSUE THREAD

**Issue by Velocity-HealthAdmin** [xamantra/momentum#25]
On version 1.2.7 i was having this issue trying to use the model.update method. It would throw an exception on the updateMomentum() method in my controller. Then i upgraded to 1.3.0, and the exception was now thrown from the momentum_base.dart file.
Then i referenced issue number two above and exported the  ref: dev-1.3.1 from the git repo, the exception now is being thrown, as shown in the screenshot attached, in the _persistModel method. I have checked all my code, and went through the documentation, cant find any reference to it. Maybe there is something wrong in my code. Kindly help and offer a solution if any please.

![Screenshot (14)](https://user-images.githubusercontent.com/54586967/88452374-82819700-ce5e-11ea-8813-70d0170dabe7.png) = The exception
![Screenshot (15)](https://user-images.githubusercontent.com/54586967/88452401-b78de980-ce5e-11ea-812d-3fdd4bdab22d.png) => the model
![Screenshot (16)](https://user-images.githubusercontent.com/54586967/88452405-ba88da00-ce5e-11ea-9401-d1eb42a68528.png) => where I'm calling the update model method
![Screenshot (17)](https://user-images.githubusercontent.com/54586967/88452408-bd83ca80-ce5e-11ea-97f2-0b66899560e1.png) => init() method.

**Comment by xamantra** [comment]
@Velocity-HealthAdmin can you show me your `persistSave` implementation in `main.dart` file? Check if you are returning a `null` value there or not. You shouldn't return `null`. You'll likely want to return `true` to tell the library that the model was persisted successfully and not throw an error.

![image](https://user-images.githubusercontent.com/37391380/88453820-1ffbbb80-ce9d-11ea-9572-a29a40d0f635.png)

**Comment by Velocity-HealthAdmin** [comment]
Good Day,

 

Thanks for the insight hey. So sorry for raising that issue, completely over looked my main.dart. I was not returning anything, hence the null. I’m so sorry. But thank you very much, issue solved. 

 

Regards.

 


Christopher Nyandoro
Systems Administrator

 <http://www.velocityhealth.co.za/> 


 


Velocity Health


Suite 28, Building 1 Prism Business Park, Ruby Close,


Fourways Sandton, 2068


t: +27 11 367 0635


m: +263 71 210 3865


e: chris@velocityhealth.co.za


 


 <http://www.velocityhealth.co.za/> www.velocityhealth.co.za

	

 


The content of this email is confidential and intended for the recipient specified in message only. It is strictly forbidden to share any part of this message with any third party, without a written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by Velocity-HealthAdmin** [comment]
Thank you very much. Somehow i overlooked my main.dart persistSave method, i wasnt returning anything. Thank for bringing that to my attention. Was so concerned about my two files, authModel and AuthController i completely did not think to look at it.
