### ISSUE TITLE
Add a way (and or option) to allow lazy loading of controller's bootstrapping when called via Momentum.controller<T>()

### ISSUE THREAD

**Issue by exts** [xamantra/momentum#26]
That was kind of a tough title, so let me expand on that.

I've notice (working on my 2nd project now) that the way I've been using momentum I don't always need to use snapshot data from momentum builder and I don't always need to disable lazy loading of controllers in the momentum configuration. Sometimes I have a screen that just uses a single method from a controller w/out accessing the model data at all and since that's the main usage of momentum builder (outside of managing the state), which means I don't necessarily need to access `snapshot` when I setup my controllers in the `InitMomentumState` method 9 times out of 10.

**Suggestion**

Allow a setting or just outright default functionality for when we call `Momentum.controller<T>(context)` to trigger bootstrap the first time its called when lazy is set to true. So you don't have to pass the controller to `controllers` property of the momentum builder in the event of not needing to use snapshot for whatever reason.

**Comment by xamantra** [comment]
VERY GOOD suggestion. I never thought of that.

Will add a parameter on the `MomentumController`.`config(...)` method.

```dart
Momentum(
  // ...
  controllers: [
    ExampleControllerA()..config(bootstrapStrategy: BootstrapStrategy.onFirstBuilder),
    ExampleControllerB()..config(bootstrapStrategy: BootstrapStrategy.onFirstCall),
  ],
  // ...
)
```

`bootstrapStrategy` will only take effect if `lazy` is `true`. The default value for the bootstrap strategy will be `BootstrapStrategy.onFirstBuilder` (which is the current behavior). So if you want to bootstrap your controller based on your suggestion, you'll have to set it to `BootstrapStrategy.onFirstCall`. The name `onFirstCall` is quite ambiguous so I'll put some detailed comment docs for both strategies.

**Comment by exts** [comment]
`BootstrapStrategy.LazyFirstBuild`
`BootstrapStrategy.LazyFirstCall`

Would be a bit more explicit imo.

**Comment by xamantra** [comment]
Was about to push my commit :)

I'll rename it.

**Comment by xamantra** [comment]
You can now check this update on your projects. Try to use the `dev-1.3.1` channel for momentum:

```yaml
dependencies:
  flutter:
    sdk: flutter
  momentum:
    git:
      url: https://github.com/xamantra/momentum.git
      ref: a6eedc0ba09d84d237a8f98b590ddb5553fd3437 # latest commit in "dev-1.3.1"
```

#### I also wrote a ready to copy example:

`main.dart`
```dart
void main() {
  runApp(
    Momentum(
      child: MyApp(),
      controllers: [
        StrategyController()..config(strategy: BootstrapStrategy.lazyFirstCall),
      ],
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Issue: #26',
      debugShowCheckedModeBanner: false,
      home: Strategy(),
    );
  }
}
``` 

`controller`
```dart
class StrategyController extends MomentumController<StrategyModel> {
  @override
  StrategyModel init() {
    return StrategyModel(
      this,
    );
  }

  String _dummyString;

  @override
  void bootstrap() {
    _dummyString = 'Hello World of Flutter!';
  }

  String getDummyString() {
    return _dummyString;
  }
}
```

`model` - just empty.
```dart
class StrategyModel extends MomentumModel<StrategyController> {
  StrategyModel(StrategyController controller) : super(controller);

  @override
  void update() {
    StrategyModel(
      controller,
    ).updateMomentum();
  }
}
```

`widget`
```dart
class Strategy extends StatelessWidget {
  const Strategy({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // access at the same time bootstrap the controller
    var controller = Momentum.controller<StrategyController>(context);
    return Scaffold(
      backgroundColor: Colors.white,
      body: MomentumBuilder(
        controllers: [], // no controllers
        builder: (context, snapshot) {
          // no usage of snapshot
          return Center(
            child: Text(controller.getDummyString()),
          );
        },
      ),
    );
  }
}
```

And we definitely don't need `MomentumBuilder` here anymore.

**Comment by exts** [comment]
Going to give it a try.

**Comment by xamantra** [comment]
You mean...

```dart
Momentum(
  // ...
  strategy: BootstrapStrategy.lazyFirstCall, // affects all controllers
  // ...
)
```

like this? It's already available.

**Comment by exts** [comment]
Oh then nice :)

**Comment by xamantra** [comment]
This update is now live on [pub.dev - v1.3.1](https://pub.dev/packages/momentum/versions/1.3.1). Will now be closed.
