### ISSUE TITLE
Suggestion: A way to redirect to the previous page

### ISSUE THREAD

**Issue by exts** [xamantra/momentum#28]
So in an app I made, [shameless plug](https://play.google.com/store/apps/details?id=com.idiotcoder.mywir), I have a situation where I can double click on an item to edit it w/out actually going to the view item entry page. The other way to update the entry is by going to the view entry (to see the description/title/date info formatted) then hitting the edit button. Well when I edit and I was on the view item page previously I'd want to redirect them there. But if I came from the index list of all the items I'd want to redirect them back to that page.

Now there's ways to do this already, even by using the new router param feature we suggested a few versions ago to pass parameter data (I'm probably going to do this for now), or just using the controller/model data and setting the page they came from whether its the view list or main list page.

This could be simplified since I'm sure you already keep track of the current route information by calling something to `Router.gotoPrev()` or `Router.prev()`

**Comment by xamantra** [comment]
Is `Router.pop(context)` not what you're looking for?

**Comment by exts** [comment]
This is why I shouldn't write suggestions at 1am.
