### ISSUE TITLE
System back button and Router

### ISSUE THREAD

**Issue by DonnC** [xamantra/momentum#30]
hello, i have been trying out Momentum and its going on well so far (its now my default state management plugin 🙂). However on using the built-in Momentum Router option i cant seem to make the system back button to work the same way as ```Router.pop(..)```
I have ```Router.pop(..)```  on the AppBar for navigating to the previous page and its working just fine when i press it. But when i use the phone system back button the app closes instead of acting like ```Router.pop(..)```.
Is there something im doing wrong

**Comment by DonnC** [comment]
aha! ```RouterPage(..)``` 😄 found it

**Comment by xamantra** [comment]
@DonnC Yes, you need to wrap your page with that widget to automatically handle the system back button. And you can override the `onWillPop:` by the way.

**Comment by DonnC** [comment]
Nice i have seen the ```onWillPop:``` . Maybe you can emphasize or add the ```RouterPage(..)``` under Router in the documentation. I had to review the listify example pages and compare with my pages to see where the difference is and thats when i saw the pages in listify example are wrapped with ```RouterPage(..)```, i visited the docs and i didnt  find any reference to ```RouterPage(..)```. Maybe that may help in the future if its in the documentation as well 😃

**Comment by xamantra** [comment]
Oh, thanks for mentioning that.
