### ISSUE TITLE
Desktop support - Feature

### ISSUE THREAD

**Issue by kovacbb** [xamantra/momentum#32]
Hi, in theory we could port the momentum to Desktop too?
That would be amazing..

**Comment by xamantra** [comment]
I'm not sure and I never tried flutter desktop either. Momentum doesn't have any platform-specific plugins so I think there's a chance it can be used on flutter desktop.

**Comment by xamantra** [comment]
@kovacbb after flutter 2.0 where the desktop is now added in the beta channel. The `flutter create` command automatically does the setup for desktop support. But in the first place, momentum doesn't have any dependencies or platform codes anyway so it should support all platforms. There's no porting needed
 
I'm currently writing a new example for momentum after the null safety migration and here's a screenshot of it running on my windows:

![image](https://user-images.githubusercontent.com/37391380/111055933-c391ee80-84b5-11eb-9bca-36ff12cc3251.png)

This example will be used in the new README overhaul.

**Comment by kovacbb** [comment]
Hey @xamantra 
That's an amazing news..
One to rule them all..
