### ISSUE TITLE
Controller can not call bootstrap & bootstrap async after reset

### ISSUE THREAD

**Issue by hienlh** [xamantra/momentum#36]
Hi, 
I met a problem in my app flow that when I logout the app, I call Momentum.resetAll(context). And then I login again. But the controller never re-call bootstrap & bootstrap async then it has not fetched new data.
How should I do in this situation?

I try to resolve this by reset _booted & _bootedAsync in this function. Is it ok?
https://github.com/xamantra/momentum/blob/ca634110824d885bd4783bd5ecc1a1036fd925b1/lib/src/momentum_base.dart#L711-L729

**Comment by xamantra** [comment]
I think you want `Momentum.restart(...)`

https://xamdev.gq/momentum/#/restart-app

**Comment by hienlh** [comment]
@xamantra Thank you, though a bit difference due to I seperated enviroment in main file, but it's work now.
