### ISSUE TITLE
Configure Router persistence

### ISSUE THREAD

**Issue by DonnC** [xamantra/momentum#37]
Hello @xamantra i know navigation persistence is a cool feature for momentum but i came across this problem
Say i have pageB() that has its controller with no persistence, and it gets some of the data it needs via RouterParam from pageA(), e.g when i press a product and i navigate to product-details-page
When i add the `persistGet` and `persistSave`, and i close the app while at pageB(), and open again..Based on persistence i will be back at pageB() but i have lost the data (passed via `RouterParam`) and i get null errors sometimes

Am i doing it wrong or there should be an option, to optionally enable Navigation persistence or not

**Comment by DonnC** [comment]
I figured i can factor out the constant Momentum persistence key for navigation 'MOMENTUM_ROUTER_HISTORY' in `persistSave` function

**Comment by DonnC** [comment]
Also realized, a particular variable was not initialized properly which was null and `Text(..)` widget was complaining

**Comment by xamantra** [comment]
If you want to persist the navigation with `MomentumRouter`, I highly suggest you create a separate controller/model for storing RouterParam data. And enable persistence on that controller.

**Comment by DonnC** [comment]
makes sense indeed thanks, i will try that
