### ISSUE TITLE
New Storage Example

### ISSUE THREAD

**Issue by kovacbb** [xamantra/momentum#39]
Hi @xamantra 
Thanks for the list-example.
It would be interesting to see some storage example, maybe together with already existing rest api example.
I'm wondering how could we chose storage provider, other then shared_preferences.
Would sqlite be possible with current implementation, as it's not key-value?
Cheers.

**Comment by xamantra** [comment]
I'm already planning this. Interestingly though, I didn't think of sqlite. I'll consider this.

**Comment by kovacbb** [comment]
Thanks.
That would be huge!
