### ISSUE TITLE
Error: The method 'inheritFromWidgetOfExactType'

### ISSUE THREAD

**Issue by sjeanph** [xamantra/momentum#40]
Hi, I was working on a project that was working before but then I decided to switch to master channel and back to beta. Now it isn't working  when I try to run and debug on vscode of use flutter run -d chrome. This is the error I'm getting:

"/C:/flutter/.pub-cache/hosted/pub.dartlang.org/momentum-1.3.3/lib/src/momentum_base.dart:1559:21: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
    return (context.inheritFromWidgetOfExactType(Momentum) as Momentum);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Failed to compile application."

I'm using flutter web by the way.

**Comment by sjeanph** [comment]
after some research I managed to fix it by changing 
return (context.inheritFromWidgetOfExactType(Momentum) as Momentum); 
to
return (context.dependOnInheritedWidgetOfExactType<Momentum>());

**Comment by xamantra** [comment]
Thanks. It seems I now need to drop depreciated calls in momentum internally.

**Comment by xamantra** [comment]
I've now released a new version on **_pub.dev_** that includes this fix.
```yaml
dependencies:
  momentum: ^1.3.5 # new updated version
```
Will now close this issue.
