### ISSUE TITLE
Model.fromJson is not a valid override of MomentumModel.fromJson 

### ISSUE THREAD

**Issue by ghost** [xamantra/momentum#50]
I updated my flutter as shown on the screenshot, and on updating the project to null safety features i see this error on every momentum model => 'ArticlesModel.fromJson' ('ArticlesModel Function(Map<String, dynamic>)') isn't a valid override of 'MomentumModel.fromJson' ('MomentumModel<MomentumController<dynamic>>? Function(Map<String, dynamic>?)').

![Screenshot (298)](https://user-images.githubusercontent.com/54586967/151711831-da4071f3-ee50-4f91-87db-17c8f2be3099.png)

![Screenshot (297)](https://user-images.githubusercontent.com/54586967/151711715-c18ff51f-9aaf-4e5a-ac1d-4cafa1b86350.png)

**Comment by xamantra** [comment]
Hello @auric-co . This is a simple issue.

You have to make your Model nullable for all `fromJson` overrides.

So that would be:
```dart
ArticlesModel? fromJson(Map<String, dynamic>? json)
{
    if (json == null) return null;
    return ArticlesModel(...);
}
```

The reason why the model and JSON are nullable is that. At the very first open of the app, everything is basically empty or has no value.

**Comment by ghost** [comment]
Thank you , fixed
