### ISSUE TITLE
To use generic factory method names

### ISSUE THREAD

**Issue by meta-boy** [xamantra/momentum#8]
https://github.com/xamantra/momentum/blob/ce9e145c26d5d8a4f3c3d8360eeeb39b66f1dd00/lib/src/momentum_base.dart#L86

It feels unnatural to have a `toJson()` method that returns a `Map` rather than a `String`. Same goes for `fromJson()`, it accepts a `Map` rather than a `JSON string`.

**Comment by xamantra** [comment]
In my experience, the method that accepts a JSON string is named `fromRawJson()` and the one that accepts map/json object is `fromJson()`.

And I think it's more accurate to call a string data source as "raw" data.

**Comment by xamantra** [comment]
I am currently making a github client and I just saw this inside `github.dart`'s source:

![image](https://user-images.githubusercontent.com/37391380/84892682-96ecaa00-b0d0-11ea-929f-b11fad8333b1.png)

I am now closing this.
